// src/app/layout.tsx
// どのページでも共通の設定が可能

import type { Metadata } from 'next'
import './globals.css'
import Header from './components/Header'
import Footer from './components/Footer'

// metadata（v12でのHead, head.tsxの集約）
export const metadata: Metadata = {
  title: 'Next13_blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="jp">
      {/* 横幅をレスポンシブにするcontainer */}
      <body className='container mx-auto bg-slate-500 text-white'>
      {/* header, footerもこのページで設定可能 */}
      <Header />
      {children}
      <Footer />
      </body>
    </html>
  )
}

/* 
・font(Interは使用しないので)削除としてのコメントアウト
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
*/