// src/app/layout.tsx
// どのページでも共通の設定が可能

import type { Metadata } from 'next'
import './globals.css'

// metadata（v12でのHead, head.tsxの集約）
export const metadata: Metadata = {
  title: 'Next13_blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="jp">
      <body>
        {/* header, footerもこのページで設定可能 */}
        <header className='text-blue-400'>Test Header from src/app/layout.tsx</header>
        
        {children}</body>
    </html>
  )
}

/* 
・font(Interは使用しないので)削除
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
*/